version: '0'
services:
 radarr:
  container_name: radarr
  restart: unless-stopped
  ports:
   - 7878:7878
  volumes:
    - <\path to data>:/config
    - <\path/to/movies>:/movies
    - <\path/to/downloadclient-downloads>:/downloads
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Etc/Zulu
  image: linuxserver/radarr
 
 sonarr:
  container_name: sonarr
  restart: unless-stopped
  ports:
   - 8989:8989
  volumes:
    - <\path to data>:/config
    - <\path/to/tv>:/tv
    - <\path/to/downloadclient-downloads>:/downloads
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Etc/Zulu
  image: linuxserver/sonarr
 
 jackett:
  container_name: jackett
  restart: unless-stopped
  ports:
   - 9117:9117
  volumes:
   - <\path to data>:/config
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Etc/Zulu
  image: linuxserver/jackett

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/Zulu
      - UMASK_SET=000 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - <\/path/to/deluge/config>:/config
      - <\/path/to/your/downloads>:/downloads
    restart: unless-stopped
