version: '3.2'
services:
 radarr:
  container_name: radarr
  restart: unless-stopped
  ports:
   - 7878:7878
  volumes:
    - mediasrv:/radarr/config
    - mediasrv:/media/movies
    - mediasrv:/deluge/downloads
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Etc/Zulu
  image: linuxserver/radarr
 
 sonarr:
  container_name: sonarr
  restart: unless-stopped
  ports:
   - 8989:8989
  volumes:
    - mediasrv:/sonarr/config
    - mediasrv:/media/tv
    - mediasrv:/deluge/downloads
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Etc/Zulu
  image: linuxserver/sonarr
 
 jackett:
  container_name: jackett
  restart: unless-stopped
  ports:
   - 9117:9117
  volumes:
   - mediasrv:/jackett/config
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Etc/Zulu
  image: linuxserver/jackett

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/Zulu
      - UMASK_SET=000 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - mediasrv:/deluge/config
      - mediasrv:/deluge/downloads
    restart: unless-stopped
    
volumes:
  mediasrv:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.41,nolock,soft,rw"
      device: ":/plex"
