version: '3.2'

services:
 radarr:
  container_name: radarr
  restart: unless-stopped
  ports:
   - 7878:7878
  volumes:
    - mediasrv/radarr/config:/radarr/config
    - mediasrv/media/movies:/media/movies
    - mediasrv/deluge/downloads:/deluge/downloads
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Etc/Zulu
  image: linuxserver/radarr
 
 sonarr:
  container_name: sonarr
  restart: unless-stopped
  ports:
   - 8989:8989
  volumes:
    - mediasrv/sonarr/config:/sonarr/config
    - mediasrv/media/shows:/media/shows
    - mediasrv/deluge/downloads:/deluge/downloads
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Etc/Zulu
  image: linuxserver/sonarr
 
 jackett:
  container_name: jackett
  restart: unless-stopped
  ports:
   - 9117:9117
  volumes:
   - mediasrv:/jackett/config
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Etc/Zulu
  image: linuxserver/jackett

 deluge:
  container_name: deluge
  restart: unless-stopped
  ports:
   - 8112:8112
   - 6881:6881
   - 6881:6881/udp
  volumes:
   - mediasrv/deluge/config:/deluge/config
   - mediasrv/deluge/downloads:/deluge/downloads
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Etc/Zulu
   - UMASK_SET=000 #optional
   - DELUGE_LOGLEVEL=error #optional
  image: linuxserver/deluge

volumes:
 mediasrv:
  driver_opts:
   type: "nfs"
   o: "addr=192.168.2.41,nolock,soft,rw"
   device: ":/plex"
